#!/usr/bin/env bash
set -Eeo pipefail
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

RED="\033[0;31m"
GREEN="\033[0;32m"
CYAN="\033[0;36m"
NOCOLOR="\033[0m"

function print_error {
  echo -e "${RED}$1${NOCOLOR}"
}

function print-step {
    echo -e "${GREEN}$1${NOCOLOR}"
}

function print-sub-step {
    echo -e "${CYAN}$1${NOCOLOR}"
}

function live-setup {
    print-step "Configuration de l'environnement live..."
    loadkeys fr-latin9
    setfont eurlatgr
    sed -i "s|#fr_FR.UTF-8 UTF-8|fr_FR.UTF-8 UTF-8|g" /etc/locale.gen
    locale-gen
    localectl set-locale fr_FR.UTF-8
    unset LANG
    source /etc/profile.d/locale.sh
}

function install {
    
    USER_ANSWER="N"
    while test "$USER_ANSWER" != "o" && test "$USER_ANSWER" != "O"; do
        print-step "Paramétrage du système : "
        fdisk -l
        echo ""
        read -e -p "Sur quel disque installer Archlinux ? : " TARGET_DISK
        read -e -p "Quel sera votre hostname : " HOSTNAME
        read -e -p "Installer les microcodes Intel ? (o/N) : " INTEL_UCODE
        read -e -p "Installer les microcodes AMD ? (o/N) : " AMD_UCODE
        read -e -p "Votre timezone (/usr/share/zoneinfo/Europe/Paris) : " TIMEZONE
        read -e -p "Souhaitez vous ajouter un utilisateur ? (nom d'utilisateur, laissez vide si aucun) : " USER_NAME
        if [ -z $INTEL_UCODE ]; then
            INTEL_UCODE="N"
        fi
        if [ -z $AMD_UCODE ]; then
            AMD_UCODE="N"
        fi
        if [ -z $TIMEZONE ]; then
            TIMEZONE="/usr/share/zoneinfo/Europe/Paris"
        fi
        echo ""
        print-step "Récapitulatif des choix :"
        print-sub-step "  * Votre disque dur cible : $TARGET_DISK"
        print-sub-step "  * Votre hostname : $HOSTNAME"
        print-sub-step "  * Installer les microcodes Intel : $INTEL_UCODE"
        print-sub-step "  * Installer les microcodes AMD : $AMD_UCODE"
        print-sub-step "  * Votre timezone : $TIMEZONE"
        if [ ! -z $USER_NAME ]; then
            print-sub-step "  * Nom de l'utilisateur supplémentaire : $USER_NAME"
        fi
        echo ""
        read -e -p "Les informations sont-elles correctes ? (o/N) : " USER_ANSWER
    done
    
    # Partitionnement
    print-step "Partitionnement du disque cible..."
    cfdisk $TARGET_DISK
    declare -a PARTITIONS=( $(fdisk -l | grep ^${TARGET_DISK}* | awk '{print $1}') )
    declare -A PART_TYPE
    declare -A PART_MOUNT_POINT
    USER_ANSWER="N"
    while test "$USER_ANSWER" != "o" && test "$USER_ANSWER" != "O"; do
        print-step "Partitions du disk cible détectées :"
        INDEX=0
        for partition in "${PARTITIONS[@]}"; do
            print-sub-step "  * Partition : $(fdisk -l | grep $partition)"
            read -e -p "Quel est le rôle de cette partition ? (1: EFI, 2: Root, 3: Home, 4: Autre (choix par défaut)) : " TYPE
            if test "$TYPE" = "1"; then
                PART_TYPE["$partition"]="EFI"
                PART_MOUNT_POINT["$partition"]="/boot/efi"
                read -e -p "Formater la partition EFI ? (o/N) : " FORMAT_EFI
                if [ -z $FORMAT_EFI ]; then
                    FORMAT_EFI="N"
                fi
                EFI_OK="o"
            elif test "$TYPE" = "2"; then
                PART_TYPE["$partition"]="ROOT"
                PART_MOUNT_POINT["$partition"]="/"
                ROOT_OK="o"
            elif test "$TYPE" = "3"; then
                PART_TYPE["$partition"]="HOME"
                PART_MOUNT_POINT["$partition"]="/home"
            else
                PART_TYPE["$partition"]="OTHER"
                read -e -p "Quel est le point de montage de cette partition ? : " MOUNT_POINT
                PART_MOUNT_POINT["$partition"]="$MOUNT_POINT"
            fi
            let INDEX=${INDEX}+1
        done
        read -e -p "Taille du swapfile ? (Exemple: 8G, laissez vide si aucun) : " SWAPFILE_SIZE
        if [ -z $EFI_OK ]; then
            echo ""
            print_error "  /!\ La partitions EFI est requise à l'installation du système."
            echo ""
            continue
        fi
        if [ -z $ROOT_OK ]; then
            echo ""
            print_error "  /!\ La partitions Root est requise à l'installation du système."
            echo ""
            continue
        fi
        echo ""
        print-step "Récapitulatif des choix :"
        for partition in "${PARTITIONS[@]}"; do
            if test "${PART_TYPE[${partition}]}" = "EFI"; then
                print-sub-step "  * Partition EFI : ${partition} (point de montage : ${PART_MOUNT_POINT[${partition}]})"
                print-sub-step "  * Formater la partition EFI : $FORMAT_EFI"
            elif test "${PART_TYPE[${partition}]}" = "ROOT"; then
                print-sub-step "  * Partition ROOT : ${partition} (point de montage : ${PART_MOUNT_POINT[${partition}]})"
            elif test "${PART_TYPE[${partition}]}" = "HOME"; then
                print-sub-step "  * Partition Home : ${partition} (point de montage : ${PART_MOUNT_POINT[${partition}]})"
            elif test "${PART_TYPE[${partition}]}" = "OTHER"; then
                print-sub-step "  * Autre partition : ${partition} (point de montage : ${PART_MOUNT_POINT[${partition}]})"
            fi
        done
        if [ ! -z $SWAPFILE_SIZE ]; then
            print-sub-step "  * Taille du swapfile : $SWAPFILE_SIZE"
        fi
        echo ""
        read -e -p "Les informations sont-elles correctes ? (o/N) : " USER_ANSWER
    done

    print-step "Formatage et montage des partitions..."
    for partition in "${PARTITIONS[@]}"; do
        if test "${PART_TYPE[${partition}]}" = "ROOT"; then
            mkfs.ext4 "${partition}"
            mkdir -p "/mnt${PART_MOUNT_POINT[${partition}]}"
            mount "${partition}" "/mnt${PART_MOUNT_POINT[${partition}]}"
        fi
    done
    for partition in "${PARTITIONS[@]}"; do
        if test "${PART_TYPE[${partition}]}" = "EFI"; then
            if test "$FORMAT_EFI" = "o" || test "$FORMAT_EFI" = "O"; then
                mkfs.vfat "${partition}"
            fi
            mkdir -p "/mnt${PART_MOUNT_POINT[${partition}]}"
            mount "${partition}" "/mnt${PART_MOUNT_POINT[${partition}]}"
        fi
    done
    for partition in "${PARTITIONS[@]}"; do
        if test "${PART_TYPE[${partition}]}" = "HOME" || test "${PART_TYPE[${partition}]}" = "OTHER"; then
            mkfs.ext4 "${partition}"
            mkdir -p "/mnt${PART_MOUNT_POINT[${partition}]}"
            mount "${partition}" "/mnt${PART_MOUNT_POINT[${partition}]}"
        fi
    done
    
    # Création du swapfile de taille spécifiée
    if [ ! -z $SWAPFILE_SIZE ]; then
        print-step "Création et activation du swapfile..."
        fallocate -l $SWAPFILE_SIZE /mnt/swapfile
        chmod 600 /mnt/swapfile
        mkswap /mnt/swapfile
        swapon /mnt/swapfile
    fi
    
    # Mise à jour des mirroirs
    print-step "Mise à jour des mirroirs..."
    reflector @/etc/xdg/reflector/reflector.conf
    
    # Installation de la base
    print-step "Installation de la base..."
    pacstrap /mnt base base-devel linux linux-firmware man-db man-pages texinfo nano vim git curl zsh zsh-completions grml-zsh-config grub os-prober efibootmgr networkmanager xdg-user-dirs
    
    # Installation des microcodes
    if test "$INTEL_UCODE" = "o" || test "$INTEL_UCODE" = "O"; then
        print-sub-step "  * Installation des microcodes Intel..."
        pacstrap /mnt intel-ucode
    fi
    if test "$AMD_UCODE" = "o" || test "$AMD_UCODE" = "O"; then
        print-sub-step "  * Installation des microcodes AMD..."
        pacstrap /mnt amd-ucode
    fi
    
    # Configuration du système
    print-step "Configuration du système..."
    genfstab -U /mnt >> /mnt/etc/fstab
    sed -i "s|#en_US.UTF-8 UTF-8|en_US.UTF-8 UTF-8|g" /mnt/etc/locale.gen
    sed -i "s|#en_US ISO-8859-1|en_US ISO-8859-1|g" /mnt/etc/locale.gen
    sed -i "s|#fr_FR.UTF-8 UTF-8|fr_FR.UTF-8 UTF-8|g" /mnt/etc/locale.gen
    sed -i "s|#fr_FR ISO-8859-1|fr_FR ISO-8859-1|g" /mnt/etc/locale.gen
    echo "LANG=fr_FR.UTF-8" > /mnt/etc/locale.conf
    echo "KEYMAP=fr-latin9" > /mnt/etc/vconsole.conf
    echo "FONT=eurlatgr" >> /mnt/etc/vconsole.conf
    echo "$HOSTNAME" > /mnt/etc/hostname
    echo "127.0.0.1 localhost" >> /mnt/etc/hosts
    echo "::1 localhost" >> /mnt/etc/hosts
    echo "127.0.1.1 $HOSTNAME.localdomain $HOSTNAME" >> /mnt/etc/hosts
    
    print-step "Configuration des locales..."
    arch-chroot /mnt ln -sf $TIMEZONE /etc/localtime
    arch-chroot /mnt locale-gen
    print-step "Configuration du réseau..."
    arch-chroot /mnt systemctl enable NetworkManager
    print-step "Installation et configuration du grub..."
    arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id="Arch Linux"
    arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
    print-step "Configuration du compte root..."
    arch-chroot /mnt chsh --shell /bin/zsh
    arch-chroot /mnt passwd
    if [ ! -z $USER_NAME ]; then
        sed -i "s|# %wheel ALL=(ALL) ALL|%wheel ALL=(ALL) ALL|g" /mnt/etc/sudoers
        arch-chroot /mnt useradd --shell=/bin/zsh --groups=wheel --create-home $USER_NAME
        print-step "Configuration du mot de passe pour l'utilisateur $USER_NAME..."
        arch-chroot /mnt passwd $USER_NAME
    fi
    
    # Démontage des partitions
    print-step "Démontage des partitions..."
    if [ ! -z $SWAPFILE_SIZE ]; then
        swapoff /mnt/swapfile
    fi
    umount -R /mnt
    echo ""
    print-step "Installation terminée ! Vous pouvez redémarrer votre système."
}

live-setup
install
