#!/bin/bash

set -e

GREEN="\033[0;32m"
CYAN="\033[0;36m"
NOCOLOR="\033[0m"

print_step() {
  echo -e "${GREEN}$1${NOCOLOR}"
}

print_sub_step() {
  echo -e "${CYAN}$1${NOCOLOR}"
}

print_step "Formatting archcraftsman..."
print_sub_step "  * Sorting imports"
isort archcraftsman launcher.py genchanges.py
print_sub_step "  * Applying black format"
black archcraftsman launcher.py genchanges.py
print_sub_step "  * Adding license headers"
addlicense -c 'Rawleenc' -f NOTICES . *.py
