#!/bin/bash

set -e

GREEN="\033[0;32m"
CYAN="\033[0;36m"
NOCOLOR="\033[0m"

print_step() {
  echo -e "${GREEN}$1${NOCOLOR}"
}

print_sub_step() {
  echo -e "${CYAN}$1${NOCOLOR}"
}

if [ -z "$1" ]; then
  echo "Usage: publish <wheel file>"
  exit 1
fi

print_sub_step "  * Checking if python wheel distribution is uploadable"
twine check $1

print_sub_step "  * Uploading python wheel distribution"
twine upload $1