#!/bin/bash

set -e

GREEN="\033[0;32m"
CYAN="\033[0;36m"
NOCOLOR="\033[0m"

print_step() {
  echo -e "${GREEN}$1${NOCOLOR}"
}

print_sub_step() {
  echo -e "${CYAN}$1${NOCOLOR}"
}

print_step "Building archcraftsman..."
print_sub_step "  * Building python wheel distribution"
rm -rf dist
python -m build --wheel