name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install pylint
      - name: Check
        run: pylint archcraftsman launcher.py

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install flake8
      - name: Check
        run: flake8 archcraftsman launcher.py

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install pyright
      - name: Check
        run: pyright archcraftsman launcher.py

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install black
      - name: Check
        run: black --check archcraftsman launcher.py

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install bandit
      - name: Check
        run: bandit -r .

  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
      - name: Setup environment
        run: go install github.com/google/addlicense@latest
      - name: Check
        run: addlicense -c 'Rawleenc' -f NOTICES -check **/*.py
  
  coverage:
    needs:
      - pylint
      - flake8
      - bandit
      - pyright
      - black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install coverage
      - name: Test
        run: |
          coverage run -m unittest
          coverage report
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
