name: Code linting
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run
        run: pylint src launcher.py

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run
        run: flake8 src launcher.py

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install pyright
      - name: Run
        run: pyright src launcher.py

  black-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run
        run: black --check src launcher.py

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run
        run: bandit -r .
