name: Run tests
on:
  workflow_run:
    workflows: 
      - "Code linting"
    branches:
      - dev
      - main
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment
        run: pip install coverage
      - name: Test
        run: |
          coverage run -m unittest
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
